# Generated by Django 4.1.4 on 2023-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.FileField(upload_to='media/blog/image'),
        ),
    ]
